spring:
  application:
    name: activityService
  mongodb:
    uri: mongodb://localhost:27017
    database: fitness-database

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

